services:
  app:
    container_name: letterboxd-backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-3001}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USERNAME: ${MYSQL_USER:-letterboxd}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-letterboxd}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-letterboxd}
      CACHE_TTL: ${CACHE_TTL:-10}
      CACHE_MAX: ${CACHE_MAX:-100}
      THROTTLER_TTL: ${THROTTLER_TTL:-60}
      THROTTLER_LIMIT: ${THROTTLER_LIMIT:-50}
      SECRET_KEY: ${SECRET_KEY:-letterboxd}
      EXPIRES_IN: ${EXPIRES_IN:-1 day}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000}
    ports:
      - "3001:3001"
    volumes:
      - ./src:/usr/app/src
      - /usr/app/node_modules  # Evita sobrescrever node_modules no container
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - letterboxd
    restart: unless-stopped
    logging:  # Configuração de logs para o serviço "app"
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mysql:
    container_name: letterboxd-db
    image: mysql:8.0  # Usando uma versão mais recente
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-letterboxd}
      MYSQL_USER: ${MYSQL_USER:-letterboxd}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-letterboxd}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - letterboxd
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    logging:  # Configuração de logs para o serviço "mysql"
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    container_name: letterboxd-redis
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning
    sysctls:
      - net.core.somaxconn=511
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - letterboxd
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
    logging:  # Configuração de logs para o serviço "redis"
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  letterboxd:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
